version: '3.7'
services:
  app:
    image: test3
    environment:
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: rootpassword
      MONGODB_HOSTNAME: mongodb
    # network_mode: host
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - backend
    
  mongodb:
    image: mongo:latest
    environment:
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: rootpassword
    # network_mode: host
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend

networks:
  # frontend:
  #   driver: bridge
  backend:
    driver: bridge

volumes:
  mongodb_data: