version: '3.7'
services:
  app:
    image: test3
    restart: unless-stopped
    env_file: 
      - .env
    environment:
      MONGODB_HOSTNAME: mongodb
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - backend
    
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    env_file: 
      - .env
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mongodb_data: