apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  APP_PORT: "5000"
  MONGODB_HOSTNAME: "db-svc"
  APP_DEBUG: "False"
  MONGO_INITDB_ROOT_USERNAME: "root"
  MONGO_INITDB_ROOT_PASSWORD: "rootpassword"
